version: '3.1'
services:

  db:
    image: postgres
    container_name: lex-project
    environment:
      POSTGRES_USER: jojocoin
      POSTGRES_PASSWORD: lex1234
    ports:
      - "5432:5432"
    volumes:
      - jojocoin_data:/var/lib/postgres

volumes:
  jojocoin_data: